# Introduction to SCIKIT-Learn(sklearn) 

This notebook demonstrate some of the most useful functions of the Scikit-learn library
0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
2. Choose the right estimator/algorithm for our problem
3. Fit the Model/Algorithm and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and Load a trained model
7. Putting it all Together

##  0. An end-to-end Scikit-Learn workflow

we will be doing all the required steps at a time then explain each later

In [3]:
# 1. Get the Data Ready
import pandas as pd
heart_disease=pd.read_csv("heart_disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2,1
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2,1
12,49,1,1,130,266,0,1,171,0,0.6,2,0,2,1
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2,1
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2,1
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2,1
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2,1
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2,1
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1
20,59,1,0,135,234,0,1,161,0,0.5,1,0,3,1
21,44,1,2,130,233,0,1,179,1,0.4,2,0,2,1
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2,1
23,61,1,2,150,243,1,1,137,1,1.0,1,0,2,1
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
26,59,1,2,150,212,1,1,157,0,1.6,2,0,2,1
27,51,1,2,110,175,0,1,123,0,0.6,2,0,2,1
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1
29,53,1,2,130,197,1,0,152,0,1.2,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,58,1,0,100,234,0,1,156,0,0.1,2,1,3,0
274,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
275,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
276,58,1,0,146,218,0,1,105,0,2.0,1,1,3,0
277,57,1,1,124,261,0,1,141,0,0.3,2,0,3,0
278,58,0,1,136,319,1,0,152,0,0.0,2,2,2,0
279,61,1,0,138,166,0,0,125,1,3.6,1,1,2,0
280,42,1,0,136,315,0,1,125,1,1.8,1,0,1,0
281,52,1,0,128,204,1,1,156,1,1.0,1,0,0,0
282,59,1,2,126,218,1,1,134,0,2.2,1,1,1,0
283,40,1,0,152,223,0,1,181,0,0.0,2,0,3,0
284,61,1,0,140,207,0,0,138,1,1.9,2,1,3,0
285,46,1,0,140,311,0,1,120,1,1.8,1,2,3,0
286,59,1,3,134,204,0,1,162,0,0.8,2,2,2,0
287,57,1,1,154,232,0,0,164,0,0.0,2,1,2,0
288,57,1,0,110,335,0,1,143,1,3.0,1,1,3,0
289,55,0,0,128,205,0,2,130,1,2.0,1,1,3,0
290,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [4]:
# Create X(features matrix)
X=heart_disease.drop("target",axis=1)

# Create Y(Labels)
Y=heart_disease["target"]

In [8]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [9]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.2)

In [10]:
clf.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [15]:
X_test.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
74,43,0,2,122,213,0,1,165,0,0.2,1,0,2
78,52,1,1,128,205,1,1,184,0,0.0,2,0,2
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1

In [18]:
Y_test.head(3)

74     1
78     1
292    0
Name: target, dtype: int64

In [17]:
Y_preds=clf.predict(X_test)
Y_preds

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1], dtype=int64)

In [19]:
# 4. Evaluate the model on the training data and test data
clf.score(X_train,Y_train)

1.0

In [20]:
clf.score(X_test,Y_test)

0.819672131147541

In [23]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(Y_test,Y_preds))

              precision    recall  f1-score   support

           0       0.69      0.86      0.77        21
           1       0.91      0.80      0.85        40

    accuracy                           0.82        61
   macro avg       0.80      0.83      0.81        61
weighted avg       0.84      0.82      0.82        61

In [24]:
confusion_matrix(Y_test,Y_preds)

array([[18,  3],
       [ 8, 32]], dtype=int64)

In [25]:
accuracy_score(Y_test,Y_preds)

0.819672131147541

In [28]:
# 5. Improve a model
# try different ammount of n_estimators
import numpy as np
np.random.seed(42)
for i in range(10,100,5):
    print(f"Trying model with {i} estimators")
    clf=RandomForestClassifier(n_estimators=i).fit(X_train,Y_train)
    print(f"Model accuracy on test set: {clf.score(X_test,Y_test)*100}%")
    print(" ")

Trying model with 10 estimators
Model accuracy on test set: 75.40983606557377%

Trying model with 15 estimators
Model accuracy on test set: 77.04918032786885%

Trying model with 20 estimators
Model accuracy on test set: 77.04918032786885%

Trying model with 25 estimators
Model accuracy on test set: 80.32786885245902%

Trying model with 30 estimators
Model accuracy on test set: 81.9672131147541%

Trying model with 35 estimators
Model accuracy on test set: 81.9672131147541%

Trying model with 40 estimators
Model accuracy on test set: 81.9672131147541%

Trying model with 45 estimators
Model accuracy on test set: 80.32786885245902%

Trying model with 50 estimators
Model accuracy on test set: 78.68852459016394%

Trying model with 55 estimators
Model accuracy on test set: 81.9672131147541%

Trying model with 60 estimators
Model accuracy on test set: 80.32786885245902%

Trying model with 65 estimators
Model accuracy on test set: 83.60655737704919%

Trying model with 70 estimators
Model accuracy on test set: 78.68852459016394%

Trying model with 75 estimators
Model accuracy on test set: 81.9672131147541%

Trying model with 80 estimators
Model accuracy on test set: 83.60655737704919%

Trying model with 85 estimators
Model accuracy on test set: 78.68852459016394%

Trying model with 90 estimators
Model accuracy on test set: 80.32786885245902%

Trying model with 95 estimators
Model accuracy on test set: 80.32786885245902%

In [29]:
# 6. Save a model and load it
import pickle
pickle.dump(clf,open("random_forest_model_1.pkl","wb"))

In [30]:
loaded_model=pickle.load(open("random_forest_model_1.pkl","rb"))
loaded_model.score(X_test,Y_test)

0.8032786885245902

## 1. Getting our data ready to be used with machone learning

Three main things we have to do:
    1. Split the data into features and labels(usually 'X' and'y')
    2. Filling(imputing) or disregarding missing values
    3. Converting non-numerical values to numerical values(feature encoding)

In [31]:
heart_disease.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1

In [32]:
X=heart_disease.drop("target",axis=1)
X.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2

In [33]:
y=heart_disease["target"]
y.head(3)

0    1
1    1
2    1
Name: target, dtype: int64

In [34]:
#Split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [35]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))